<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die(); ?>
<?php

/**
 * @global CMain $APPLICATION
 */

?>
<?php $APPLICATION->IncludeComponent(
	"intec.universe:main.footer", 
	"template.1", 
	array(
		"SETTINGS_USE" => "Y",
		"PRODUCTS_VIEWED_SHOW" => "N",
		"PRODUCTS_VIEWED_LAZYLOAD_USE" => "N",
		"REGIONALITY_USE" => "N",
		"CONTACTS_USE" => "Y",
		"CONTACTS_IBLOCK_TYPE" => "content",
		"CONTACTS_IBLOCK_ID" => "135",
		"CONTACTS_REGIONALITY_USE" => "Y",
		"CONTACTS_REGIONALITY_STRICT" => "N",
		"MENU_MAIN_ROOT" => "bottom",
		"MENU_MAIN_CHILD" => "footer",
		"MENU_MAIN_LEVEL" => "4",
		"SEARCH_NUM_CATEGORIES" => "1",
		"SEARCH_TOP_COUNT" => "5",
		"SEARCH_ORDER" => "date",
		"SEARCH_USE_LANGUAGE_GUESS" => "Y",
		"SEARCH_CHECK_DATES" => "N",
		"SEARCH_SHOW_OTHERS" => "N",
		"SEARCH_INPUT_ID" => "footer-search",
		"SEARCH_TIPS_USE" => "N",
		"SEARCH_MODE" => "site",
		"LOGOTYPE_PATH" => "/include/logotype.intec.php",
		"LOGOTYPE_LINK" => "https://okgbi.ru/",
		"CONTACTS_PROPERTY_CITY" => "CITY",
		"CONTACTS_PROPERTY_ADDRESS" => "ADDRESS",
		"CONTACTS_PROPERTY_PHONE" => "PHONE",
		"CONTACTS_PROPERTY_EMAIL" => "EMAIL",
		"CONTACTS_PROPERTY_REGION" => "REGIONS",
		"PHONE_VALUE" => "+7 (000) 000 00 00",
		"PRODUCTS_VIEWED_IBLOCK_MODE" => "multi",
		"ADDRESS_VALUE" => "г. Челябинск",
		"EMAIL_VALUE" => "shop@example.com",
		"COPYRIGHT_VALUE" => "Очаковский комбинат ЖБИ &copy; #YEAR# Все права защищены",
		"FORMS_CALL_ID" => "2",
		"FORMS_CALL_TEMPLATE" => ".default",
		"SOCIAL_VK_LINK" => "https://vk.com/okgbi",
		"SOCIAL_FACEBOOK_LINK" => "",
		"SOCIAL_INSTAGRAM_LINK" => "",
		"SOCIAL_TWITTER_LINK" => "",
		"LOGOTYPE_SHOW" => "Y",
		"PHONE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE_SHOW" => "Y",
		"PRODUCTS_VIEWED_TITLE" => "Ранее вы смотрели",
		"PRODUCTS_VIEWED_PAGE_ELEMENT_COUNT" => "10",
		"PRODUCTS_VIEWED_COLUMNS" => "4",
		"PRODUCTS_VIEWED_SHOW_NAVIGATION" => "Y",
		"ADDRESS_SHOW" => "Y",
		"EMAIL_SHOW" => "Y",
		"COPYRIGHT_SHOW" => "Y",
		"FORMS_CALL_SHOW" => "Y",
		"FORMS_CALL_TITLE" => "Заказать звонок",
		"MENU_MAIN_SHOW" => "Y",
		"SEARCH_SHOW" => "Y",
		"SOCIAL_SHOW" => "Y",
		"THEME" => "light",
		"TEMPLATE" => "template.4",
		"ICONS" => array(
			0 => "ALFABANK",
			1 => "SBERBANK",
			2 => "VTBBANK",
			3 => "GAZPROMBANK",
			4 => "QIWI",
			5 => "MIR",
			6 => "VISA",
			7 => "MASTERCARD",
			8 => "",
		),
		"CONSENT_URL" => "/about/consent/",
		"CATALOG_URL" => "/catalog/",
		"SEARCH_URL" => "/search/",
		"PRODUCTS_VIEWED_PRICE_CODE" => array(
			0 => "BASE",
		),
		"SEARCH_CATEGORY_0" => array(
			0 => "no",
		),
		"SEARCH_PRICE_CODE" => array(
			0 => "BASE",
		),
		"SEARCH_PRICE_VAT_INCLUDE" => "Y",
		"SEARCH_CURRENCY_CONVERT" => "N",
		"COMPONENT_TEMPLATE" => "template.1",
		"CONTACTS_ELEMENTS" => array(
			0 => "",
			1 => "",
		),
		"CONTACTS_ELEMENT" => "",
		"PRODUCTS_VIEWED_IBLOCK_TYPE" => "content",
		"PRODUCTS_VIEWED_IBLOCK_ID" => "",
		"SOCIAL_YOUTUBE_LINK" => "https://www.youtube.com/channel/UCSYMbekM0ZIpUtjyxsqzvSg/",
		"SOCIAL_ODNOKLASSNIKI_LINK" => "",
		"PRODUCTS_VIEWED_CONVERT_CURRENCY" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_16" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_58" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_62" => "N",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_113" => "N",
		"SEARCH_CATEGORY_0_TITLE" => "",
		"PRODUCTS_VIEWED_SHOW_PRODUCTS_138" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"COPYRIGHT_SHOW_SUBDOMAINS" => "Y",
		"SOCIAL_WHATSAPP_LINK" => "whatsapp://send?phone=+79670590816&text=%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%B9+%D0%B4%D0%B5%D0%BD%D1%8C%21+%F0%9F%91%8B+%D0%9F%D0%B8%D1%88%D1%83+%D0%92%D0%B0%D0%BC+%D1%81+%D1%81%D0%B0%D0%B9%D1%82%D0%B0+okgbi.ru",
		"SOCIAL_TELEGRAM_LINK" => "tg://resolve?domain=+79670590816",
		"SUBDOMAINS" => "Y"
	),
	false
); ?>